// THIS IS AN AUTOGENERATED FILE.
// DO NOT EDIT THIS FILE DIRECTLY.
export default { data: ["javascript","gridsome","nuxt","firebase","eslint","experience","amp","typescript","react","reasonml","programming","testing"] };
