// THIS IS AN AUTOGENERATED FILE.
// DO NOT EDIT THIS FILE DIRECTLY.
export default { data: ['non-technical', 'lesson-learned', 'javascript', 'gridsome', 'nuxt', 'firebase', 'eslint', 'experience', 'amp', 'programming', 'typescript', 'react', 'reasonml', 'testing'] }
