// THIS IS AN AUTOGENERATED FILE.
// DO NOT EDIT THIS FILE DIRECTLY.
module.exports = ['3-years-3-different-company', 'lesson-learned-from-building-tokopedia-anniv-microsite', 'the-art-of-deleting-and-updating-the-code', 'generate-amp-pages-in-nuxtjs', 'tasting-reasonml-for-react', 'migrate-nuxt-to-typescript', 'unit-testing-guide-in-vuejs', 'create-awesome-blog-with-gridsome', 'experience-in-become-fasilitator-gdk-mws-2018', 'create-simple-like-button-using-firebase-rtdb', 'eslint-formatter-html-extended']
