
// THIS IS AN AUTOGENERATED FILE.
// DO NOT EDIT THIS FILE DIRECTLY.
export default {
  data: ['tokopedia-tech-interview-process', 'learn-programming-for-non-tech', 'every-working-environtment-is-unique', 'cara-saya-belajar-teknologi-baru']
}
