// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
export default {
  data: ['cara-saya-belajar-teknologi-baru', 'every-working-environtment-is-unique', 'learn-programming-for-non-tech', 'tokopedia-tech-interview-process']
}
