const fs = require('fs-extra')
const path = require('path')
const FOLDER_DRAFTS = '../contents/drafts/'

function generateData () {
  fs.readdir(path.resolve(FOLDER_DRAFTS), function (err, filenames) {
    if (err) {
      console.log('Error on read folder drafts', err)
      return
    }
    let strResult = ''
    let result = []
    filenames.forEach(function (filename) {
      const pathDir = path.join(path.resolve(FOLDER_DRAFTS), filename)
      const isDir = fs.lstatSync(pathDir).isDirectory()
      if (isDir) {
        result.push(filename)
      }
    })

    strResult = `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
module.exports = ${JSON.stringify(result)}
    `
    writeFile(strResult)
  })
}

function writeFile (content) {
  const stream = fs.createWriteStream(path.resolve('../contents/drafts/index.js'))
  stream.write(content)
  stream.end()
}

// run in first attempt
generateData()
