const fs = require('fs-extra')
const path = require('path')
const FOLDER_DRAFTS = path.resolve('./contents/drafts/')

function generateData () {
  console.log('folder drafts: ', FOLDER_DRAFTS)
  fs.readdir(FOLDER_DRAFTS, function (err, filenames) {
    if (err) {
      console.log('Error on read folder drafts', err)
      return
    }
    let strResult = ''
    let result = []
    filenames.forEach(function (filename) {
      const pathDir = path.join(FOLDER_DRAFTS, filename)
      const isDir = fs.lstatSync(pathDir).isDirectory()
      if (isDir) {
        result.push(filename)
      }
    })

    strResult = `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
export default { data: ${JSON.stringify(result)} }
    `
    writeFile(strResult)
  })
}

function writeFile (content) {
  const stream = fs.createWriteStream(path.resolve('./contents/drafts/index.js'))
  stream.write(content)
  stream.end()
}

// run in first attempt
generateData()
